CREATE TABLE image_vectors (
    image_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_name VARCHAR2(255),
    image_data BLOB,             -- stockage de l’image brute
    embedding VECTOR(512),       -- vecteur d’encodage
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT image_name, image_data
FROM image_vectors
WHERE image_id = 2;

CREATE TABLE image_vectors_test (
    image_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_name VARCHAR2(255),
    image_data BLOB,             -- stockage de l’image brute
    embedding VECTOR(512),       -- vecteur d’encodage
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT *
FROM image_vectors_test;


SELECT
  iv.image_id, IV.image_name , IVT.image_name,
  ROUND(VECTOR_DISTANCE(IV.embedding, IVT.embedding, COSINE), 2) AS score
FROM image_vectors IV
CROSS JOIN image_vectors_test IVT
WHERE IVT.image_id = 1
ORDER BY VECTOR_DISTANCE(IV.embedding, IVT.embedding, COSINE) ASC
FETCH FIRST 5 ROWS ONLY;

