CREATE TABLE image_vectors (
    image_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_name VARCHAR2(255),
    image_data BLOB,             -- stockage de l’image brute
    embedding VECTOR(512),       -- vecteur d’encodage
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT image_name, image_data
FROM image_vectors
WHERE image_id = 2;

CREATE TABLE image_vectors_test (
    image_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_name VARCHAR2(255),
    image_data BLOB,             -- stockage de l’image brute
    embedding VECTOR(512),       -- vecteur d’encodage
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT *
FROM image_vectors_test;

select count(*) from diabetic_retinopathy_diagnosis;


--EXPLAIN PLAN FOR


with test as (
    select d.image_id, d.embedding, d.image_data, d.image_name
    from diabetic_retinopathy_diagnosis d
    where d.image_id = 5
)

SELECT
  drd.image_id, drd.image_name , t.image_name, drd.image_data,
  ROUND(VECTOR_DISTANCE(drd.embedding, t.embedding, COSINE), 2) AS score
FROM diabetic_retinopathy_diagnosis drd
CROSS JOIN test t
ORDER BY VECTOR_DISTANCE(drd.embedding, t.embedding, COSINE) ASC
FETCH FIRST 10 ROWS ONLY;

--SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);






desc diabetic_retinopathy_diagnosis;
desc patient_cases;






--EXPLAIN PLAN FOR
SELECT
  iv.image_id, IV.image_name , IVT.image_name, iv.image_data,
  ROUND(VECTOR_DISTANCE(IV.embedding, IVT.embedding, COSINE), 2) AS score
FROM image_vectors IV
CROSS JOIN image_vectors_test IVT
WHERE IVT.image_id = 1
ORDER BY VECTOR_DISTANCE(IV.embedding, IVT.embedding, COSINE) ASC
FETCH FIRST 5 ROWS ONLY;

--SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);


